### ISSUE TITLE
Investigate how spectra gets coadded in the pipeline.

### ISSUE THREAD

**Issue by austingulliver** [austingulliver/chiron_slicer#1]
Adding the ability to coad stellar exposure from the same star across multiple nights is an important feature that the pipeline needs to support. Currently, the pipeline only supports coadd across a single night but not multiple.

**Comment by Edison1999** [comment]
Multiple tests have been carried out to understand better the coadding issue. Since the pipeline does not support adding across multiple nights, we have tested the coadding behavior by introducing stellar exposures and ThAr files from a different night into the night that the program is reducing.

 For example, we execute the program for night 230201 by introducing stellar exposures from a different night into the directory of 230201 and renaming the files so the dates match.

 It has been observed that although the program combines the spectra, it produces a combined 1D spectrum that is wavelength-shifted. 


Email to Dr. Gulliver for the latest test (2023-09-25);

The results obtained have changed from what we discussed on Friday. I think that the problem concerns the ThAr files that we are using to perform the wavelength calibration. I reduced the 230201 night with four different ThAr files (I only kept one ThAr in the folder when I completed the reduction). The picture at below shows the results zoom in for a peak



![Image](https://github.com/austingulliver/chiron_slicer/assets/66285897/4339d5e2-1ebe-4e9e-825b-a59060517516)



 
black line => 2023 night reduction using only 1148 ThAr file from the same night. 
blue line => 2023 night reduction using only 1166 ThAr file from the same night.
red line => 2023 night reduction using only 1163 ThAr file from night 210723.
green line => 2023 night reduction using only 1162 ThAr file from night 220212.

The shift can be clearly seen for the results of processing the data with a different ThAr. Even using the  ThAr files from the same night produce a shift in the wavelength.
