### ISSUE TITLE
Combine stellar and individual reduction

### ISSUE THREAD

**Issue by austingulliver** [austingulliver/chiron_slicer#19]
Create one command to produce both combine stellar spectrum and individual reduction in results folder.

**Comment by Edison1999** [comment]
How combine_stellar work?

To execute combine_Stellar the following command is used 

reduce_slicer,'220210', /post_process, /combine_stellar

The execution tree when /combine_stellar is true results in the following 

In Sorting hat if keyword_set (combine_stellar) and (redpar.remove_crs eq 0.5
- Stellar exposures are reduced individually instead of combining them 
Otherwise 
- Stellar exposures are combined first and then reduced. -> How are they combined? 
               *  For each different start -> Create data_cube[] (stack pixel intensities dimensions 1432, 4112, #stellar 
                   exposure ) -> Find average of each exposure individually -> Find the average of the exposure average and 
                   call it common_avg ->  data_cube[*,*,index] =   mean(img, /double) /common_avg.
               *  weighted_master_frame method is called which contracts the n-dimensional cube to 1 dimension by taking 
                   the average in a cascade top-down approach.
               * CTIO_SPEC is then called -> Output is in chiron\tous\mir7\iodspec\... directory 



1) if keyword_set (combine_stellar) and (redpar.remove_crs eq 0.5)  then  combine reduction is performed in reduce_slicer.pro
              * It seems that the routine is only written to work with only a single stellar spectra?? Need to investigate more
